/* eslint-disable */
/**
 * Generated data model types.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.16.5.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import { AnyDataModel } from "convex/server";
import type { GenericId } from "convex/values";

/**
 * The names of all of your Convex tables.
 */
export type TableNames = "agents" | "cronJobs" | "memories" | "portfolioSnapshots" | "positions" | "tasks" | "trades";

/**
 * The type of a document stored in Convex.
 */
export type Doc<TableName extends TableNames> = TableName extends "agents"
  ? {
    _id: GenericId<"agents">;
    _creationTime: number;
    name: string;
    role: string;
    description: string;
    status: "idle" | "working" | "offline";
    avatar: string;
    lastActive: number;
    tasksCompleted: number;
  }
  : TableName extends "cronJobs"
  ? {
    _id: GenericId<"cronJobs">;
    _creationTime: number;
    name: string;
    schedule: string;
    description: string;
    lastRun?: number;
    nextRun?: number;
    status: "active" | "paused" | "error";
  }
  : TableName extends "memories"
  ? {
    _id: GenericId<"memories">;
    _creationTime: number;
    title: string;
    content: string;
    tags: string[];
    priority: "🔴" | "🟡" | "🟢";
    createdAt: number;
    updatedAt: number;
  }
  : TableName extends "portfolioSnapshots"
  ? {
    _id: GenericId<"portfolioSnapshots">;
    _creationTime: number;
    timestamp: number;
    totalValue: number;
    cashBalance: number;
    unrealizedPnl: number;
    realizedPnl: number;
  }
  : TableName extends "positions"
  ? {
    _id: GenericId<"positions">;
    _creationTime: number;
    market: string;
    side: "yes" | "no";
    shares: number;
    entryPrice: number;
    currentPrice: number;
    unrealizedPnl: number;
    isActive: boolean;
  }
  : TableName extends "tasks"
  ? {
    _id: GenericId<"tasks">;
    _creationTime: number;
    title: string;
    description: string;
    assignee: "Stuart" | "Micky";
    priority: "low" | "medium" | "high" | "critical";
    status: "backlog" | "in-progress" | "done";
    createdAt: number;
    updatedAt: number;
  }
  : TableName extends "trades"
  ? {
    _id: GenericId<"trades">;
    _creationTime: number;
    market: string;
    side: "yes" | "no";
    shares: number;
    price: number;
    amount: number;
    type: "buy" | "sell";
    timestamp: number;
  }
  : never;

/**
 * The type of an insert into a Convex table.
 * Replace optional fields with optional values and strip the `_id` and `_creationTime` fields.
 */
export type Insert<TableName extends TableNames> = Omit<Doc<TableName>, "_id" | "_creationTime">;

/**
 * The names of indexes defined on this table.
 */
export type IndexNames<TableName extends TableNames> = TableName extends "memories"
  ? "search_content"
  : never;

/**
 * A type representing your Convex data model.
 *
 * This is the type that is used with your Convex client.
 */
export interface DataModel extends AnyDataModel {
  agents: {
    document: Doc<"agents">;
    fieldPaths: "_id" | "_creationTime" | "name" | "role" | "description" | "status" | "avatar" | "lastActive" | "tasksCompleted";
    indexes: {};
    searchIndexes: {};
    vectorIndexes: {};
  };
  cronJobs: {
    document: Doc<"cronJobs">;
    fieldPaths: "_id" | "_creationTime" | "name" | "schedule" | "description" | "lastRun" | "nextRun" | "status";
    indexes: {};
    searchIndexes: {};
    vectorIndexes: {};
  };
  memories: {
    document: Doc<"memories">;
    fieldPaths: "_id" | "_creationTime" | "title" | "content" | "tags" | "priority" | "createdAt" | "updatedAt";
    indexes: {};
    searchIndexes: {
      search_content: {
        searchField: "content";
        filterFields: never;
      };
    };
    vectorIndexes: {};
  };
  portfolioSnapshots: {
    document: Doc<"portfolioSnapshots">;
    fieldPaths: "_id" | "_creationTime" | "timestamp" | "totalValue" | "cashBalance" | "unrealizedPnl" | "realizedPnl";
    indexes: {};
    searchIndexes: {};
    vectorIndexes: {};
  };
  positions: {
    document: Doc<"positions">;
    fieldPaths: "_id" | "_creationTime" | "market" | "side" | "shares" | "entryPrice" | "currentPrice" | "unrealizedPnl" | "isActive";
    indexes: {};
    searchIndexes: {};
    vectorIndexes: {};
  };
  tasks: {
    document: Doc<"tasks">;
    fieldPaths: "_id" | "_creationTime" | "title" | "description" | "assignee" | "priority" | "status" | "createdAt" | "updatedAt";
    indexes: {};
    searchIndexes: {};
    vectorIndexes: {};
  };
  trades: {
    document: Doc<"trades">;
    fieldPaths: "_id" | "_creationTime" | "market" | "side" | "shares" | "price" | "amount" | "type" | "timestamp";
    indexes: {};
    searchIndexes: {};
    vectorIndexes: {};
  };
}