/* eslint-disable */
/**
 * Generated utilities for implementing server-side Convex query and mutation functions.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.16.5.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import {
  ActionBuilder,
  MutationBuilder,
  QueryBuilder,
  SchemaDefinition,
  TableDefinition,
} from "convex/server";
import type { DataModel } from "./dataModel.js";

/**
 * Define a query in this Convex app's public API.
 *
 * This function will be allowed to read your Convex database and will be accessible from the client.
 */
export declare const query: QueryBuilder<DataModel, "public">;

/**
 * Define a mutation in this Convex app's public API.
 *
 * This function will be allowed to modify your Convex database and will be accessible from the client.
 */
export declare const mutation: MutationBuilder<DataModel, "public">;

/**
 * Define an action in this Convex app's public API.
 *
 * An action can run any JavaScript code, including non-deterministic code and code with side-effects.
 */
export declare const action: ActionBuilder<DataModel, "public">;

/**
 * Define an internal query function.
 *
 * This function will be allowed to read from your Convex database. It will not be accessible from the client.
 */
export declare const internalQuery: QueryBuilder<DataModel, "internal">;

/**
 * Define an internal mutation function.
 *
 * This function will be allowed to modify your Convex database. It will not be accessible from the client.
 */
export declare const internalMutation: MutationBuilder<DataModel, "internal">;

/**
 * Define an internal action function.
 *
 * An action can run any JavaScript code, including non-deterministic code and code with side-effects.
 * This function will not be accessible from the client.
 */
export declare const internalAction: ActionBuilder<DataModel, "internal">;